=== davefutyan/common_sw/program_params/resources/program_params_schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" >

<xs:element name="program_params" type="program_params_type" />

<xs:complexType name="program_params_type">
  <xs:sequence>
	<xs:element name="param"  type="param_type"  minOccurs="0" maxOccurs="unbounded"/>
	<xs:element name="module" type="module_type" minOccurs="0" maxOccurs="unbounded"/>
  </xs:sequence>
</xs:complexType>	


<xs:complexType name="module_type">
  <xs:sequence>
	<xs:element name="name"   type="name_type"/>
	<xs:element name="param"  type="param_type"   minOccurs="0" maxOccurs="unbounded"/>
	<xs:element name="module" type="module_type"  minOccurs="0" maxOccurs="unbounded"/>
  </xs:sequence>
</xs:complexType>	

<xs:complexType name="param_type">
  <xs:sequence>
	<xs:element name="name"       type="name_type"/>
    <xs:element name="short_name" type="short_name_type" minOccurs="0"/>
	<xs:element name="value"      type="xs:string"       minOccurs="0"/>
	<xs:element name="type"       type="value_data_type" minOccurs="0" default="string"/>
	<xs:element name="help"       type="xs:string"       minOccurs="0"/>
	<xs:element name="min"        type="xs:string"       minOccurs="0"/>
	<xs:element name="max"        type="xs:string"       minOccurs="0"/>
	<xs:element name="repeatable" type="xs:boolean"      minOccurs="0" default="false"/>
  </xs:sequence>
</xs:complexType>	

<xs:simpleType  name="name_type">
    <xs:restriction base="xs:string">
	  <xs:minLength value="1"/>
    </xs:restriction>
</xs:simpleType>

<xs:simpleType  name="short_name_type">
	<xs:restriction base="xs:string">
		<xs:minLength value="1"/>
		<xs:maxLength value="1"/>
    </xs:restriction>
</xs:simpleType>

<xs:simpleType name="value_data_type">
	<xs:restriction base="xs:string">
		<xs:enumeration value="string" />
		<xs:enumeration value="int"    />
		<xs:enumeration value="double" />
		<xs:enumeration value="bool"   />
	</xs:restriction>
</xs:simpleType>

</xs:schema>

=== davefutyan/common_sw/fits_data_model/conf/py_fits_data_model.xml
<?xml version="1.0" encoding="UTF-8"?>

<program_params xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="program_params_schema.xsd">

<param>
	<name>input_files</name>
	<short_name>i</short_name>
	<help>a list of fsd files</help>
</param>

<param>
    <name>output_code_dir</name>
    <short_name>s</short_name>
    <value>results</value>
    <help>the name of the directory to which code files are written. Source files are written to the sub-directory src, whild header files are written to the sub-directory include.</help>
</param>

<param>
    <name>output_doc_dir</name>
    <short_name>d</short_name>
    <value>results</value>
    <help>the name of the directory to which Doxygen documentation files are written.</help>
</param>

</program_params>

=== davefutyan/common_sw/program_params/tests/unit_test/conf/TestModules.xml
<?xml version="1.0" encoding="UTF-8"?>

<program_params xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="program_params_schema.xsd">
<param>
	<name>CommandLine</name>
</param>


<module>
	<name>TestModule</name>
	<param>
		<name>StringParam</name>
		<value>test string</value>
		<type>string</type>
		<help>This is the help of the StringParam</help>
		<min>t</min>
		<max>u</max>
	</param>
	
	<param>
		<name>IntParam</name>
		<value>456</value>
		<type>int</type>
		<help>This is the help of the IntParam</help>
		<min>456</min>
		<max>456</max>
	</param>
	
	<param>
		<name>DoubleParam</name>
		<value>-1.65e-4</value>
		<type>double</type>
		<help>This is the help of the Double</help>
		<min>-2</min>
		<max>0</max>
	</param>
	
	<module>
		<name>Level2</name>
		<param>
			<name>BoolParam</name>
			<value>true</value>
			<type>bool</type>
			<help>This is the help of the BoolParam</help>
		</param>
	</module>
</module>
</program_params>

=== davefutyan/common_sw/program_params/tests/unit_test/conf/TestParameters.xml
<?xml version="1.0" encoding="UTF-8"?>

<program_params xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="program_params_schema.xsd">

<param>
	<name>MinDefParam</name>
</param>

 <param>
	<name>CommandLine</name>
</param>

<param>
	<name>StringParam</name>
	<value>test string</value>
	<type>string</type>
	<help>This is the help of the StringParam</help>
	<min>t</min>
	<max>u</max>
</param>

<param>
    <name>StringVectorParam</name>
	<value>test string</value>
    <type>string</type>
    <help>This is the help of the String Vector Param</help>
    <min>t</min>
    <max>u</max>
    <repeatable>true</repeatable>
</param>

<param>
	<name>IntParam</name>
	<value>456</value>
	<type>int</type>
	<help>This is the help of the Int Param</help>
	<min>456</min>
	<max>456</max>
</param>

<param>
    <name>IntVectorParam</name>
	<value>456</value>
    <type>int</type>
    <help>This is the help of the Int Vector Param</help>
	<min>456</min>
	<max>456</max>
    <repeatable>true</repeatable>
</param>

<param>
	<name>DoubleParam</name>
	<value>-1.65e-4</value>
	<type>double</type>
	<help>This is the help of the Double</help>
	<min>-2</min>
	<max>0</max>
</param>

<param>
    <name>DoubleVectorParam</name>
    <value>-1.65e-4</value>
    <type>double</type>
    <help>This is the help of the Double Vector Param</help>
    <min>-2</min>
    <max>0</max>
    <repeatable>true</repeatable>
</param>

<param>
	<name>BoolParam</name>
	<value>true</value>
	<type>bool</type>
	<help>This is the help of the BoolParam</help>
</param>

<param>
    <name>BoolVectorParam</name>
    <value>true</value>
    <type>bool</type>
    <help>This is the help of the Bool Vector Param</help>
    <repeatable>true</repeatable>
</param>


</program_params>

=== davefutyan/common_sw/program_params/tests/unit_test/conf/TestDefaultValueParams.py.xml
<?xml version="1.0" encoding="UTF-8"?>

<program_params xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="program_params_schema.xsd">

<param>
	<name>MinDefParam</name>
</param>

 <param>
	<name>CommandLine</name>
</param>

<!-- Parameters without default values -->

<param>
	<name>StringParam</name>
	<short_name>s</short_name>
	<value>test string</value>
	<type>string</type>
	<help>This is the help of the StringParam</help>
	<min>t</min>
	<max>u</max>
</param>

<param>
    <name>StringVectorParam</name>
	<short_name>t</short_name>
	<value>test string</value>
    <type>string</type>
    <help>This is the help of the String Vector Param</help>
    <repeatable>true</repeatable>
</param>

<param>
	<name>IntParam</name>
	<short_name>i</short_name>
	<value>465</value>
	<type>int</type>
	<help>This is the help of the Int Param</help>
</param>

<param>
    <name>IntVectorParam</name>
	<short_name>j</short_name>
	<value>465</value>
    <type>int</type>
    <help>This is the help of the Int Vector Param</help>
    <repeatable>true</repeatable>
</param>

<param>
	<name>DoubleParam</name>
	<short_name>d</short_name>
	<value>-1.65e-4</value>
	<type>double</type>
	<help>This is the help of the Double</help>
</param>

<param>
    <name>DoubleVectorParam</name>
	<short_name>e</short_name>
    <value>-1.65e-4</value>
    <type>double</type>
    <help>This is the help of the Double Vector Param</help>
    <repeatable>true</repeatable>
</param>

<param>
	<name>BoolParam</name>
	<short_name>b</short_name>
	<value>False</value>
	<type>bool</type>
	<help>This is the help of the BoolParam</help>
</param>

<param>
    <name>BoolVectorParam</name>
	<short_name>c</short_name>
    <value>False</value>
    <type>bool</type>
    <help>This is the help of the Bool Vector Param</help>
    <repeatable>true</repeatable>
</param>


</program_params>

=== davefutyan/common_sw/fits_data_model/conf/fits_data_model.xml
<?xml version="1.0" encoding="UTF-8"?>

<program_params xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="program_params_schema.xsd">


<param>
	<name>input</name>
	<short_name>i</short_name>
	<help>input fits schema file (*.fsd)</help>
</param>

<param>
	<name>source_output_dir</name>
	<short_name>s</short_name>
	<value>src</value>
	<help>directory to store the source file</help>
</param>

<param>
	<name>header_output_dir</name>
	<short_name>o</short_name>
	<value>include</value>
	<help>directory to store the header file</help>
</param>

</program_params>

=== davefutyan/common_sw/fits_data_model/tests/unit_test/conf/TestPyFitsWrapper.xml
<?xml version="1.0" encoding="UTF-8"?>

<program_params xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="program_params_schema.xsd">

<param>
    <name>input_files</name>
    <short_name>i</short_name>
    <value>../resources/SCI_PRW_SubArray.fsd</value>
    <help>a list of fsd files</help>
</param>

<param>
    <name>output_src_dir</name>
    <short_name>s</short_name>
    <value>results</value>
    <help></help>
</param>

<param>
    <name>output_doc_dir</name>
    <short_name>d</short_name>
    <value>results</value>
    <help></help>
</param>

</program_params>
