=== davefutyan/common_sw/utilities/resources/trigger_file_schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="cheops:gs" targetNamespace="cheops:gs" elementFormDefault="qualified" attributeFormDefault="unqualified">
    
    <xs:annotation>
        <xs:documentation>Schema for monitor4EO trigger files.</xs:documentation>
    </xs:annotation>
     
    <xs:simpleType name="eeDateTime">
        <xs:annotation>
            <xs:documentation>Date time with format UTC=2011-10-30T17:23:00</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:pattern value="(UTC=9999-99-99T99:99:99)|(UTC=(([1-3][0-9]{3}))((0[1-9])|(1[012]))((0[1-9])|([12][0-9])|(3[01]))T(([01][0-9])|(2[0-3]))([0-5][0-9])([0-5][0-9]))|(UTC=(([1-3][0-9]{3}))-((0[1-9])|(1[012]))-((0[1-9])|([12][0-9])|(3[01]))T(([01][0-9])|(2[0-3]))(:[0-5][0-9])(:[0-5][0-9]))|(UTC=((0[1-9])|([12][0-9])|(3[01]))-(jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec)-(([1-3][0-9]{3})) (([01][0-9])|(2[0-3]))(:[0-5][0-9])(:[0-5][0-9])\.[0-9]{3})"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:complexType name="Earth_Explorer_HeaderType">
        <xs:sequence>
            <xs:element name="Fixed_Header" type="Fixed_HeaderType">
                <xs:annotation>
                    <xs:documentation>The EE Fixed Header</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="Variable_Header" type="Variable_HeaderType">
                <xs:annotation>
                    <xs:documentation>The EE (optional) Variable Header</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="Fixed_HeaderType">
        <xs:annotation>
            <xs:documentation>Definition of the fixed header</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="File_Name" type="xs:string">
                <xs:annotation>
                    <xs:documentation>Name of the file
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="File_Description" type="xs:string"/>
            <xs:element name="Notes" type="xs:string"/>
            <xs:element name="Mission" type="xs:string">
            </xs:element>
            <xs:element name="File_Class" type="xs:string">
                <xs:annotation>
                    <xs:documentation>OPER/SVT/TEST</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="File_Type" type="xs:string">
            </xs:element>
            <xs:element name="Validity_Period">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="Validity_Start" type="eeDateTime">
                            <xs:annotation>
                                <xs:documentation>Depending on the contents of the file, this might be either the validaty start time or the date of the first data element </xs:documentation>
                            </xs:annotation>
                        </xs:element>
                        <xs:element name="Validity_Stop" type="eeDateTime">
                            <xs:annotation>
                                <xs:documentation>Validity Stop time or date of the last data element</xs:documentation>
                            </xs:annotation>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="File_Version" type="xs:string"/>
            <xs:element name="Source">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="System" type="xs:string"/>
                        <xs:element name="Creator" type="xs:string"/>
                        <xs:element name="Creator_Version" type="xs:string"/>
                        <xs:element name="Creation_Date" type="eeDateTime"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="Variable_HeaderType">
        <xs:annotation>
            <xs:documentation>EE variable header type for the Datatake Order List type</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="PASS_ID"      type="xs:string"/>
            <xs:element name="PREV_PASS_ID" type="xs:string"/>
            <xs:element name="PROGTYPE"     type="xs:unsignedByte"/>
            <xs:element name="PROG_ID"      type="xs:unsignedShort"/>
            <xs:element name="REQ_ID"       type="xs:unsignedShort"/>
            <xs:element name="VISITCTR"     type="xs:unsignedByte"/>
            <xs:element name="OBSID"        type="xs:unsignedInt"/>
            <xs:element name="PROC_NUM"     type="xs:int"/>
            <xs:element name="PROC_NUM_OUT" type="xs:int"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="Earth_Explorer_FileType">
        <xs:sequence>
            <xs:element name="Earth_Explorer_Header" type="Earth_Explorer_HeaderType"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:element name="Earth_Explorer_File" type="Earth_Explorer_FileType"/>
</xs:schema>

=== davefutyan/common_sw/utilities/doxygen/trigger_file_example.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<Earth_Explorer_File xmlns="cheops:gs" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="cheops:gs trigger_file_schema.xsd">
  <Earth_Explorer_Header>
    <Fixed_Header>
      <File_Name>CH_PR990001_TG000101_PS18010118_TU2020-01-01T01-01-01_TRIGGER-testProcessor-test_V0000</File_Name>
      <File_Description/>
      <Notes/>
      <Mission>CHEOPS</Mission>
      <File_Class/>
      <File_Type>TRIGGER</File_Type>
      <Validity_Period>
        <Validity_Start>UTC=2020-01-01T01:01:01</Validity_Start>
        <Validity_Stop>UTC=2022-01-01T01:01:01</Validity_Stop>
      </Validity_Period>
      <File_Version>0000</File_Version>
      <Source>
        <System>SOC</System>
        <Creator>testProcessor</Creator>
        <Creator_Version>1.0</Creator_Version>
        <Creation_Date>UTC=2017-05-12T08:12:04</Creation_Date>
      </Source>
    </Fixed_Header>
    <Variable_Header>
      <PASS_ID>18010118</PASS_ID>
      <PREV_PASS_ID>18010112</PREV_PASS_ID>
      <PROGTYPE>99</PROGTYPE>
      <PROG_ID>1</PROG_ID>
      <REQ_ID>1</REQ_ID>
      <VISITCTR>1</VISITCTR>
      <OBSID>1</OBSID>
      <PROC_NUM>0</PROC_NUM>
      <PROC_NUM_OUT>0</PROC_NUM_OUT>
    </Variable_Header>
  </Earth_Explorer_Header>
</Earth_Explorer_File>
